Added pre commit logic and storybooks static to gitignore

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,1 +1,17 @@
-pnpm build && pnpm storybook:build
+echo "Running pre-commit hook"
+
+commands=("pnpm build"
+          "pnpm storybook:build"     
+          )
+
+for cmd in "${commands[@]}"; do
+    echo "Running: $cmd"
+    $cmd || {
+        echo "Command failed: $cmd"
+        exit 1
+    }
+done
+
+echo "All pre-commmit checks passed!"
+
+
